-- 已作廢（v107）：
-- 原版使用 `ADD CONSTRAINT IF NOT EXISTS`（PostgreSQL 不支援，會語法錯誤），
-- 而且會把 weight 設為 NULL，但 catches.weight 是 NOT NULL。
-- supabase-schema.sql 建表時已包含 check (weight > 0 and weight < 100)，不需要再執行。
